### ISSUE TITLE
Can't adjust intensity in Dirt Rally 2.0

### ISSUE THREAD

**Issue by Johnth10** [araghon007/X1nput#12]
Hello,

I love this mod, cause I love impulse triggers. The mod works on Dirt Rally 2.0, but I find it too strong. So I used "X1nput.ini" and put it in same directory as the dlls. But when I edit it, there is no difference ingame. Can you help me ?

Thank you

**Comment by araghon007** [comment]
Closing issues relating to old X1nput (sorry for not responding originally)
