### ISSUE TITLE
It dosen' work with xbox series x controller

### ISSUE THREAD

**Issue by Jerome-comienzo** [araghon007/X1nput#13]
please fix it. thank you!!

**Comment by Johnth10** [comment]
It works on mine

**Comment by araghon007** [comment]
Could you check if the new version works with the Xbox Series X controller? I really hope it does

**Comment by kisould** [comment]
The new version didn't work when I was playing Forza Hrizon 4 steam version with Xbox Series X controller.

**Comment by araghon007** [comment]
Does the controller vibrate if you select the controller and press Test in the X1nput Configurator?

**Comment by kisould** [comment]
Yes, every thing is ok before this step.

**Comment by araghon007** [comment]
Do you have any other games you could test it with?

**Comment by kisould** [comment]
It seems that only FH4 has this problem. I tried it with Nioh 2 and the injecting succeed without crashing.

**Comment by araghon007** [comment]
I'd suggest making a separate issue for FH4 then

**Comment by araghon007** [comment]
I have bought an Xbox Series X controller, tested over USB, wireless dongle and Bluetooth, and even on my laptop and it works fine, so I'll be closing this issue.
