### ISSUE TITLE
Assetto Corsa Competizione compatibility?

### ISSUE THREAD

**Issue by Denco96** [araghon007/X1nput#15]
Hi,

Does this work with ACC? I've tried putting the .dll file where the executable is, but the FFB is still coming from my controller, not the impulse triggers.

**Comment by SweetyVolty** [comment]
I made it work it should be the default one. put the 64 bit one in the directory (you can use task manager to find out where its hidden while game (sim whatever) is open. then close and put XInput1_3.dll and X1nput.ini (to customize) in that directory. 

It was kinda ugly though. I deleted the ACC beacuse it/I cannot played with a xb1 controller, not even close to the AC.

**Comment by araghon007** [comment]
Closing issues relating to old X1nput
