### ISSUE TITLE
Vibration problem

### ISSUE THREAD

**Issue by STG2005** [araghon007/X1nput#27]
When I play Forza Horizon 4 on steam and use xinput 2.0, the vibration of the controller disappears and only the triggers vibrate, also the LT vibrates when I go on land, without pressing it or anything.

**Comment by araghon007** [comment]
Well, X1nput 2.0 is discontinued at this point, but the fact that it would cause normal rumble motors to not work is pretty weird. I'll be closing this issue since I won't continue development on that version regardless.
