### ISSUE TITLE
Steam games crashing on controller disconnect (GameOverlayRenderer.dll)

### ISSUE THREAD

**Issue by araghon007** [araghon007/X1nput#6]
So I managed to debug a few games this happened with, and the issue happens with Steam's Game Overlay Renderer (both 32-bit and 64-bit).
I'm thinking a temporary solution could be replacing Steam's xinput as well.

**Comment by araghon007** [comment]
Happens even with Steam's overlay disabled.

**Comment by CookiePLMonster** [comment]
Is this relevant? This is likely a threading issue, as the code has still a lot of non thread-safe segments.

**Comment by araghon007** [comment]
Seems to still be the case, though it's weird that it only happens with some games running on steam. I wonder if this would happen with some non-steam games launched through steam as well, I'll check that out later.
As for thread-safety, I'm a real novice at C/C++, so all help is appreciated. I'll probably work on this project again once I'll have more time.
I'll merge your pull request, thanks!

**Comment by CookiePLMonster** [comment]
Steam Overlay likes to mess with XInput, so threading issue is even more likely then!

**Comment by CookiePLMonster** [comment]
Can you list games you observed this issue with? I tried with GTA San Andreas and did not encounter issues, but since it's pretty much a single threaded game I assume that's why it works fine for me. Would be good to be able to test it with some game which crashes frequently during this event.

**Comment by araghon007** [comment]
No more WinRT
