### ISSUE TITLE
Windows 1903 Update Breaks Game Support

### ISSUE THREAD

**Issue by Halliphax** [araghon007/X1nput#8]
Unknown if isolated to just this game (still testing will update if more are found).
Fallout 4 Impulse Triggers worked with 1809. However, when updating to 1903 the game hangs (white screens) then crashes to desktop.

Interestingly, SkyrimSE (which uses an incredibly similar, though previous version of the same engine as Fallout 4) works fine on both 1809 and 1903.

**Comment by CookiePLMonster** [comment]
I kinda expect all those issues reported to be down to threading... or WinRT initialization not really working fine with some of those games (hopefully not).

**Comment by araghon007** [comment]
Closing issues relating to old X1nput
