### ISSUE TITLE
Unity3d Engine

### ISSUE THREAD

**Issue by Rorschach1219** [araghon007/X1nput#9]
I am currently using unity3d to develop games. How can I use this DLL? My application is based on uwp

**Comment by araghon007** [comment]
With UWP, you can use WGI directly 
https://docs.microsoft.com/en-us/windows/uwp/gaming/input-for-games
https://docs.microsoft.com/en-us/windows/uwp/gaming/gamepad-and-vibration

**Comment by Rorschach1219** [comment]
@araghon007  I'm not developing directly on the uwp platform, I'm developing in the unity engine and exporting the uwp program from the engine. So I can't use the native uwp

**Comment by araghon007** [comment]
Sorry for late replies,
I don't think it's possible to use 3rd party DLLs with UWP, but you should be able to use UWP APIs in Unity through WinRT
https://docs.unity3d.com/Manual/windowsstore-scripts.html
